plugins {
    id 'java'
    id 'io.github.reqstool.gradle-plugin' version '0.1.0'
}

group = 'io.github.reqstool.example'
version = '0.1.0'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation 'io.github.reqstool:reqstool-java-annotations:1.0.0'
    annotationProcessor 'io.github.reqstool:reqstool-java-annotations:1.0.0'
    testCompileOnly 'io.github.reqstool:reqstool-java-annotations:1.0.0'
    testAnnotationProcessor 'io.github.reqstool:reqstool-java-annotations:1.0.0'

    testImplementation platform('org.junit:junit-bom:6.0.3')
    testImplementation 'org.junit.jupiter:junit-jupiter-api'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

testing {
    suites {
        test {
            useJUnitJupiter()
        }

        integrationTest(JvmTestSuite) {
            sources {
                java {
                    srcDirs = ['src/integration-test/java']
                }
            }
            dependencies {
                implementation project()
            }
            targets {
                all {
                    testTask.configure {
                        shouldRunAfter(test)
                    }
                }
            }
        }
    }
}

configurations {
    integrationTestImplementation.extendsFrom implementation, testImplementation
    integrationTestCompileOnly.extendsFrom compileOnly, testCompileOnly
    integrationTestAnnotationProcessor.extendsFrom annotationProcessor, testAnnotationProcessor
    integrationTestRuntimeOnly.extendsFrom runtimeOnly, testRuntimeOnly
}

tasks.named('check') {
    dependsOn(testing.suites.integrationTest)
}

requirementsTool {
    datasetPath = file('docs/reqstool')
    testResults = ['build/test-results/**/*.xml']
}

tasks.named('build') {
    finalizedBy tasks.named('assembleRequirements')
}

tasks.named('assembleRequirements') {
    dependsOn test, testing.suites.integrationTest
}
