package io.github.reqstool.gradle;

import org.gradle.api.Project;
import org.gradle.api.file.RegularFileProperty;
import org.gradle.api.provider.ListProperty;
import org.gradle.api.provider.Property;

/**
 * Extension for configuring the Reqstool Gradle Plugin. Provides zero-configuration
 * defaults matching the Maven plugin behavior.
 */
public class RequirementsToolExtension {

	private final RegularFileProperty requirementsAnnotationsFile;

	private final RegularFileProperty svcsAnnotationsFile;

	private final RegularFileProperty outputDirectory;

	private final RegularFileProperty datasetPath;

	private final ListProperty<String> testResults;

	private final Property<Boolean> skip;

	private final Property<Boolean> skipAssembleZipArtifact;

	private final Property<Boolean> skipAttachZipArtifact;

	public RequirementsToolExtension(Project project) {
		this.requirementsAnnotationsFile = project.getObjects().fileProperty();
		this.svcsAnnotationsFile = project.getObjects().fileProperty();
		this.outputDirectory = project.getObjects().fileProperty();
		this.datasetPath = project.getObjects().fileProperty();
		this.testResults = project.getObjects().listProperty(String.class);
		this.skip = project.getObjects().property(Boolean.class);
		this.skipAssembleZipArtifact = project.getObjects().property(Boolean.class);
		this.skipAttachZipArtifact = project.getObjects().property(Boolean.class);

		// Set defaults matching
		this.requirementsAnnotationsFile.convention(project.getLayout()
			.getBuildDirectory()
			.file("generated/sources/annotationProcessor/java/main/resources/annotations.yml"));
		this.svcsAnnotationsFile.convention(project.getLayout()
			.getBuildDirectory()
			.file("generated/sources/annotationProcessor/java/test/resources/annotations.yml"));
		this.outputDirectory.convention(project.getObjects()
			.fileProperty()
			.fileProvider(project.getLayout().getBuildDirectory().map(d -> d.dir("reqstool").getAsFile())));
		this.datasetPath.convention(project.getLayout().getProjectDirectory().file("reqstool"));

		// Gradle default test results pattern
		this.testResults.convention(project.provider(() -> {
			return java.util.Arrays.asList("build/test-results/**/*.xml");
		}));

		this.skip.convention(false);
		this.skipAssembleZipArtifact.convention(false);
		this.skipAttachZipArtifact.convention(false);
	}

	/**
	 * Returns the path to the requirements annotations YAML file generated by the annotation
	 * processor.
	 * @return file property for requirements annotations
	 */
	public RegularFileProperty getRequirementsAnnotationsFile() {
		return requirementsAnnotationsFile;
	}

	/**
	 * Returns the path to the SVCs (Software Verification Cases) annotations YAML file
	 * generated by the test annotation processor.
	 * @return file property for SVCs annotations
	 */
	public RegularFileProperty getSvcsAnnotationsFile() {
		return svcsAnnotationsFile;
	}

	/**
	 * Returns the output directory where the ZIP artifact and combined annotations are
	 * written.
	 * @return file property for the output directory
	 */
	public RegularFileProperty getOutputDirectory() {
		return outputDirectory;
	}

	/**
	 * Returns the dataset directory containing {@code requirements.yml} and optional
	 * supporting files.
	 * @return file property for the dataset directory
	 */
	public RegularFileProperty getDatasetPath() {
		return datasetPath;
	}

	/**
	 * Returns the list of Ant-style glob patterns used to locate test result XML files.
	 * @return list property of test result patterns
	 */
	public ListProperty<String> getTestResults() {
		return testResults;
	}

	/**
	 * Returns whether the entire plugin execution should be skipped.
	 * @return boolean property; {@code true} skips all plugin tasks
	 */
	public Property<Boolean> getSkip() {
		return skip;
	}

	/**
	 * Returns whether ZIP artifact assembly should be skipped while still combining
	 * annotations.
	 * @return boolean property; {@code true} skips ZIP assembly
	 */
	public Property<Boolean> getSkipAssembleZipArtifact() {
		return skipAssembleZipArtifact;
	}

	/**
	 * Returns whether attaching the ZIP artifact for Maven publishing should be skipped.
	 * @return boolean property; {@code true} skips artifact attachment
	 */
	public Property<Boolean> getSkipAttachZipArtifact() {
		return skipAttachZipArtifact;
	}

}
