# yaml-language-server: $schema=https://raw.githubusercontent.com/asciidoctor/asciidoctor-intellij-plugin/main/src/main/resources/jsonSchemas/antoraPlaybookSchema.json
# For local development only. Published site: https://reqstool.github.io

site:
  title: Reqstool Gradle Plugin
  url: https://reqstool.github.io/reqstool-java-gradle-plugin
  start_page: reqstool-java-gradle-plugin::index.adoc

content:
  sources:
    - url: ~+
      branches: HEAD
      start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll
asciidoc:
  attributes:
    kroki-server-url: https://kroki.io
    kroki-fetch-diagram: true
  extensions:
    - asciidoctor-kroki
