on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Build
        run: ./gradlew clean build
